// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYTCV3XcwqDioMcxS0nVo4u-vFvi2X-g',
    appId: '1:734538137018:web:f8ec3612b5957f01e2f183',
    messagingSenderId: '734538137018',
    projectId: 'babylon-login-7e3fa',
    authDomain: 'babylon-login-7e3fa.firebaseapp.com',
    storageBucket: 'babylon-login-7e3fa.firebasestorage.app',
    measurementId: 'G-BH448V08LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSa43MZcQmMJOruMYV_MVBW4vZndHa2MM',
    appId: '1:734538137018:android:6758c48df64a7a92e2f183',
    messagingSenderId: '734538137018',
    projectId: 'babylon-login-7e3fa',
    storageBucket: 'babylon-login-7e3fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFX0ggzb4ZIcOl_09IoaUR2CD98bhVn8I',
    appId: '1:734538137018:ios:38aa2c7b9f2ab259e2f183',
    messagingSenderId: '734538137018',
    projectId: 'babylon-login-7e3fa',
    storageBucket: 'babylon-login-7e3fa.firebasestorage.app',
    iosBundleId: 'com.example.babylonLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFX0ggzb4ZIcOl_09IoaUR2CD98bhVn8I',
    appId: '1:734538137018:ios:38aa2c7b9f2ab259e2f183',
    messagingSenderId: '734538137018',
    projectId: 'babylon-login-7e3fa',
    storageBucket: 'babylon-login-7e3fa.firebasestorage.app',
    iosBundleId: 'com.example.babylonLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsYTCV3XcwqDioMcxS0nVo4u-vFvi2X-g',
    appId: '1:734538137018:web:5247b156742b6c6ce2f183',
    messagingSenderId: '734538137018',
    projectId: 'babylon-login-7e3fa',
    authDomain: 'babylon-login-7e3fa.firebaseapp.com',
    storageBucket: 'babylon-login-7e3fa.firebasestorage.app',
    measurementId: 'G-XY8NYX1JL8',
  );
}
